[package]
name = "hollow"
version = "0.0.0"
edition = "2021"

[dependencies]
winit = "0.30"
wgpu = "27.0"
pollster = "0.4"
bytemuck = { version = "1.24", features = [ "derive", "min_const_generics" ] }
take_mut = "0.2.2"
rand = "0.9.2"
web-time = "1.1.0"
